#spring:
#  datasource:
#    url: 'jdbc:mysql://localhost:3306/cjs?characterEncoding=UTF-8&&serverTimezone=GMT'
#    username: 'root'
#    password: 'root'
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  security:
#    user:
#      name: gy
#      password: 1234
#      roles: [ROLE_ADMIN]
#
#
#
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.cjs.proj.pojo
#
#
#
##pagehelper分页插件配置 以下属性不加也可以实现分页功能
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#
